# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('tax_code', models.IntegerField(default=1)),
                ('amount', models.IntegerField(default=1)),
                ('tax_amount', models.IntegerField(default=1)),
                ('total_amount', models.IntegerField(default=1)),
            ],
        ),
    ]
