# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxobject',
            name='tax_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taxobject',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=10),
        ),
    ]
