# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-09-13 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20180912_1655'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taxobject',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='taxobject',
            name='tax_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='taxobject',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=3, default=1, max_digits=10),
        ),
    ]
